### ISSUE TITLE
stringi won't compile on Redhat 6.7 with R 3.4.2

### ISSUE THREAD

**Issue by bindatype** [gagolews/stringi#315]
Hi, 

I need to get stringr installed but it uses stringi as a dependency. We currently have stringi 1.1.6 installed but need at least 1.1.7. I've tried upgrading with install.packages("stringr") but get the following message:
```
g++ -std=gnu++11 -I/c1/apps/R/3.4.2/lib64/R/include -DNDEBUG -I. -Iicu61       -Iicu61/unicode -Iicu61/common       -Iicu61/i18n -DU_STATIC_IMPLEMENTATION       -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -DU_CHARSET_IS_UTF8=0 -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -I/usr/local/include  -DU_CHARSET_IS_UTF8=0 -fpic -fpic  -g -O2 -c icu61/i18n/number_affixutils.cpp -o icu61/i18n/number_affixutils.o
In file included from icu61/i18n/number_types.h:14:0,
                 from icu61/i18n/number_affixutils.h:11,
                 from icu61/i18n/number_affixutils.cpp:8:
icu61/unicode/numberformatter.h:688:21: error: ‘icu_61::number::Notation::Notation’ names constructor
icu61/unicode/numberformatter.h:1072:20: error: ‘icu_61::number::Rounder::Rounder’ names constructor
icu61/unicode/numberformatter.h:1110:20: error: ‘icu_61::number::Rounder::Rounder’ names constructor
icu61/unicode/numberformatter.h:1146:20: error: ‘icu_61::number::Rounder::Rounder’ names constructor
make: *** [icu61/i18n/number_affixutils.o] Error 1
ERROR: compilation failed for package ‘stringi’
* removing ‘/c1/apps/R/3.4.2/lib64/R/library/stringi’
* restoring previous ‘/c1/apps/R/3.4.2/lib64/R/library/stringi’

The downloaded source packages are in
	‘/home/maclach/.Rtmp/RtmpkfkAls/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("stringi", type = "source") :
  installation of package ‘stringi’ had non-zero exit status
```

Any idea how to get around this issue?

**Comment by gagolews** [comment]
I guess you're using a quite out-dated version of gcc (`gcc -v` == ?)

You could try installing either a quite recent version of the `libicu-devel` rpm on your system (version >= 55) or upgrading gcc.

**Comment by bindatype** [comment]
Yes, I was compiling with gcc 4.7.4 while getting these errors. I switched to gcc 5.2.1 and the package installed without any problem. Thanks so much!
